// <auto-generated />
using System;
using System.Collections.Generic;
using CSharpPostgresMastery.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CSharpPostgresMastery.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251229115443_InitialCreateWithAdvancedTypes")]
    partial class InitialCreateWithAdvancedTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CSharpPostgresMastery.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Genres")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Author = "George Orwell",
                            Genres = new List<string> { "Dystopian", "Political Fiction" },
                            Price = 120000m,
                            Properties = "{\"Pages\":328,\"Publisher\":\"Secker \\u0026 Warburg\",\"Language\":\"English\"}",
                            Title = "1984",
                            Year = 1949
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Author = "Harper Lee",
                            Genres = new List<string> { "Fiction", "Classic" },
                            Price = 150000m,
                            Properties = "{\"Pages\":281,\"Publisher\":\"J. B. Lippincott \\u0026 Co.\"}",
                            Title = "To Kill a Mockingbird",
                            Year = 1960
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Author = "F. Scott Fitzgerald",
                            Genres = new List<string> { "Tragedy", "Classic" },
                            Price = 100000m,
                            Properties = "{\"Pages\":180}",
                            Title = "The Great Gatsby",
                            Year = 1925
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
